FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Override CMD to ensure binding to 0.0.0.0 for Docker accessibility
CMD ["npx", "live-server", "./", "--port=3000", "--host=0.0.0.0", "--entry-file=index.html", "--no-browser"]