version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"   # expose DB để kết nối từ host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: volunteerhub   # tạo sẵn DB
    volumes:
      - pgdata:/var/lib/postgresql/data  # volume lưu dữ liệu postgres

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Lưu dữ liệu redis (tùy chọn)

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redis_data:
